services:

  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - front
    networks:
      - app_network

  api:
    build: ./api
    env_file:
      - api/.env
    ports:
      - "8000:8000"
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - app_network


  front:
    build: ./front
    environment:
      - API_HOST=api
      - API_PORT=8000
    ports:
      - "8501:8501"
    volumes:
      - ./front:/app
    depends_on:
      - api
    security_opt:
      - seccomp:unconfined
    networks:
      - app_network

  postgis:
    build: 
      context: ./postgis
      # platforms:
      #   - linux/arm64
    ports:
      - "5432:5432"
    networks:
      - app_network
    environment:
      - POSTGRES_USER=mapper
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=overture
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_omf_data:/var/lib/postgresql/data
      - ./postgis/data:/backup
    user: postgres
    command: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mapper", "-d", "overture"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg_omf_data:

networks:
  app_network:
    driver: bridge
