# HOLDER HYPERPARAMETERS
RANDOM_SEED = 42
FREEZE_EMBEDDINGS = True
VERBOSE = True
HIDDEN_DIM = 128
NUM_LAYERS = 1
MARGIN = 0.5
LEARNING_RATE = 0.00001
NUM_EPOCHS = 3
MODEL_NAME = "mlx-geoprompt-v0.1"
PROJECTION_DIM = 64
 